### ISSUE TITLE
Update Issue: Failed to Build

### ISSUE THREAD

**Issue by prathamvbhat** [mjakeman/extension-manager#653]
**Describe the bug**
When ever i try to update the extension-manager i get a failed error which tell me that build failed. I have pasted the error in Additional context. 

**System Information:**
 - Endavour OS (Arch Based)
 - extension-manager-0.5.1
 - AUR (yay)

**Additional context**
FAILED: src 
/usr/bin/blueprint-compiler batch-compile src/. ../extension-manager-0.5.1/src ../extension-manager-0.5.1/src/exm-window.blp ../extension-manager-0.5.1/src/exm-installed-page.blp ../extension-manager-0.5.1/src/exm-browse-page.blp ../extension-manager-0.5.1/src/exm-extension-row.blp ../extension-manager-0.5.1/src/exm-search-row.blp ../extension-manager-0.5.1/src/exm-detail-view.blp ../extension-manager-0.5.1/src/exm-screenshot.blp ../extension-manager-0.5.1/src/exm-comment-tile.blp ../extension-manager-0.5.1/src/exm-comment-dialog.blp ../extension-manager-0.5.1/src/exm-rating.blp ../extension-manager-0.5.1/src/exm-upgrade-assistant.blp ../extension-manager-0.5.1/src/exm-error-dialog.blp ../extension-manager-0.5.1/src/exm-info-bar.blp ../extension-manager-0.5.1/src/exm-info-bar-item.blp ../extension-manager-0.5.1/src/exm-screenshot-view.blp
Traceback (most recent call last):
  File "/usr/bin/blueprint-compiler", line 38, in <module>
    from blueprintcompiler import main
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/main.py", line 27, in <module>
    from . import formatter, interactive_port, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/interactive_port.py", line 25, in <module>
    from . import decompiler, parser, tokenizer
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/decompiler.py", line 26, in <module>
    from .gir import *
  File "/usr/lib/python3.12/site-packages/blueprintcompiler/gir.py", line 25, in <module>
    import gi  # type: ignore
    ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gi/__init__.py)
[37/75] Generating GObject enum file src/exm-enums.h (wrapped by meson because command contains newlines, to capture output)
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: extension-manager-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
extension-manager - exit status 4

**Comment by oscfdezdz** [comment]
According to the logs, it seems that the problem is related to `blueprint-compiler` package, do you get the same log every time? From what I've seen in the [AUR comments](https://aur.archlinux.org/packages/extension-manager), the issues may be because of the GCC version change in Arch to version 14 and more specifically with `text-engine` package. See https://github.com/mjakeman/text-engine/issues/37

**Comment by prathamvbhat** [comment]
whenever i try to update it, it dosent update. It just gives me this error

**Comment by oscfdezdz** [comment]
Does it still happen with the latest versions?

**Comment by prathamvbhat** [comment]
Hi there,
As I have moved from Endavor OS to Arch Linux, which still comes under Arch based OS. I'm have not encountered this issue in my current OS (Arch Linux).

If I face any issue I will reach out to you.
Thank you for your time and understanding.

**Comment by oscfdezdz** [comment]
I'll close this issue then, feel free to open a new one if it happens 😄
